//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitecturalStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchitecturalStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator pracownika,Imię,Nazwisko,Data urodzenia,Telefon,Identyfikator kontraktu,Uprawnienia do nadzoru,Pesel.
        /// </summary>
        internal static string Generator_Architects_Csv_Header {
            get {
                return ResourceManager.GetString("Generator_Architects_Csv_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator projektu,Nazwa projektu,Identyfikator podmiotu,Rodzaj projektu,Koszt,Data rozpoczęcia,Data zakończenia,Identyfikator projektu architektonicznego.
        /// </summary>
        internal static string Generator_OuterProjects_Csv_Header {
            get {
                return ResourceManager.GetString("Generator_OuterProjects_Csv_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator podmiotu,Imię,Nazwisko,Numer telefonu.
        /// </summary>
        internal static string Generator_OuterSubjects_Csv_Header {
            get {
                return ResourceManager.GetString("Generator_OuterSubjects_Csv_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../../data/.
        /// </summary>
        internal static string Global_Data_Path {
            get {
                return ResourceManager.GetString("Global_Data_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2137.
        /// </summary>
        internal static string Global_Random_Seed {
            get {
                return ResourceManager.GetString("Global_Random_Seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =====================================.
        /// </summary>
        internal static string Program_CustomGenerator_BreakLine {
            get {
                return ResourceManager.GetString("Program_CustomGenerator_BreakLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ile nadzorów ma zostać wygenerowanych?.
        /// </summary>
        internal static string Program_CustomGenerator_Ile_nadzorów_ma_zostać_wygenerowanych_ {
            get {
                return ResourceManager.GetString("Program_CustomGenerator_Ile_nadzorów_ma_zostać_wygenerowanych_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ile projektów ma zostać wygenerowanych?.
        /// </summary>
        internal static string Program_CustomGenerator_Ile_projektów_ma_zostać_wygenerowanych_ {
            get {
                return ResourceManager.GetString("Program_CustomGenerator_Ile_projektów_ma_zostać_wygenerowanych_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ile zewnętrznych podmiotów ma zostać wygenerowanych?.
        /// </summary>
        internal static string Program_CustomGenerator_Ile_zewnętrznych_podmiotów_ma_zostać_wygenerowanych_ {
            get {
                return ResourceManager.GetString("Program_CustomGenerator_Ile_zewnętrznych_podmiotów_ma_zostać_wygenerowanych_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ile zewnętrznych projektów ma zostać wygenerowanych?.
        /// </summary>
        internal static string Program_CustomGenerator_Ile_zewnętrznych_projektów_ma_zostać_wygenerowanych_ {
            get {
                return ResourceManager.GetString("Program_CustomGenerator_Ile_zewnętrznych_projektów_ma_zostać_wygenerowanych_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilu architektów ma zostać wygenerowanych?.
        /// </summary>
        internal static string Program_CustomGenerator_Ilu_architektów_ma_zostać_wygenerowanych_ {
            get {
                return ResourceManager.GetString("Program_CustomGenerator_Ilu_architektów_ma_zostać_wygenerowanych_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilu klientów ma zostać wygenerowanych?.
        /// </summary>
        internal static string Program_CustomGenerator_Ilu_klientów_ma_zostać_wygenerowanych_ {
            get {
                return ResourceManager.GetString("Program_CustomGenerator_Ilu_klientów_ma_zostać_wygenerowanych_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przejdźmy do okresu t1-t2:.
        /// </summary>
        internal static string Program_CustomGenerator_Przejdźmy_do_okresu_t1_t2_ {
            get {
                return ResourceManager.GetString("Program_CustomGenerator_Przejdźmy_do_okresu_t1_t2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teraz zostaną wygenerowane dane. Proszę czekać.
        /// </summary>
        internal static string Program_CustomGenerator_Teraz_zostaną_wygenerowane_dane__Proszę_czekać {
            get {
                return ResourceManager.GetString("Program_CustomGenerator_Teraz_zostaną_wygenerowane_dane__Proszę_czekać", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj w generatorze danych do studia architektonicznego!.
        /// </summary>
        internal static string Program_CustomGenerator_Witaj_w_generatorze_danych_do_studia_architektonicznego_ {
            get {
                return ResourceManager.GetString("Program_CustomGenerator_Witaj_w_generatorze_danych_do_studia_architektonicznego_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zacznijmy do okresu t0-t1:.
        /// </summary>
        internal static string Program_CustomGenerator_Zacznijmy_do_okresu_t0_t1_ {
            get {
                return ResourceManager.GetString("Program_CustomGenerator_Zacznijmy_do_okresu_t0_t1_", resourceCulture);
            }
        }
    }
}
